<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cl.duoc.backendiii</groupId>
    <artifactId>banco-xyz-bff-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Banco XYZ - Proyecto Multi-modulo BFF</name>
    <description>Proyecto padre que agrupa el batch y los 3 BFF (Web, Movil, Cajero) del Banco XYZ.</description>

    <modules>
        <module>batch-core</module>
        <module>common-data</module>
        <module>bff-web</module>
        <module>bff-movil</module>
        <module>bff-cajero</module>
    </modules>

</project>