spring.application.name=spring-batch-semana1-legacy-migration

# Spring Batch necesita tablas de metadatos para registrar JobInstance, JobExecution y StepExecution.
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# Conexión a MySQL local (banco_xyz_batch)
spring.datasource.url=jdbc:mysql://localhost:3306/banco_xyz_batch?useSSL=false&serverTimezone=America/Santiago
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
# Reduce ruido en consola y muestra lo relevante del flujo batch.
logging.level.root=INFO
logging.level.cl.duoc.backendiii.semana1=INFO
logging.level.org.springframework.batch.core.step.AbstractStep=INFO

spring.batch.job.name=procesarTransaccionesJob

# Configuración del Job 3 (Estados de Cuenta Anuales)
app.estado-anual.total-records=1000
app.estado-anual.grid-size=4