server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/banco_xyz_batch
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-local

movil.security.username=app.movil
movil.security.password=MovilXYZ2026!
movil.security.jwt.secret=ClaveSecretaSuperLargaParaFirmarJWTBancoXYZ2026SemanaCinco
movil.security.jwt.expiration-ms=3600000